#!/bin/sh

################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2011 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

# setup alsa (especially the mixer config)

mixer() {
  parm=${4:-on}
  amixer -c "$1" sset "$2" "$3" $parm >/dev/null 2>&1
  amixer -c "$1" sset "$2" $parm >/dev/null 2>&1
}

(
. /etc/profile

logger -t ALSA "Setting up sound card"

if [ -f /etc/sound.conf ]; then

  alsactl restore -f /etc/sound.conf

else

# set common mixer params
  mixer 0 Master 100%
  mixer 0 Front 100%
  mixer 0 PCM 100%

# Only unmute Line and Aux if they are possibly used.
#  mixer 0 Line 100%
#  mixer 0 Aux 100%

  mixer 0 Surround 100%

# DRC
#  mixer 0 'Dynamic Range Compression' 90%

# some notebooks use headphone instead of master
  mixer 0 Headphone 100%

  mixer 0 Center 100%
  mixer 0 LFE 100%

# set digital output mixer params
  mixer 0 'IEC958' 100% on
  mixer 0 'IEC958 Output' 100%
  mixer 0 'IEC958 Coaxial' 100%
  mixer 0 'IEC958 LiveDrive' 100%
  mixer 0 'IEC958 Optical Raw' 100%
  mixer 0 'SPDIF Out' 100%
  mixer 0 'SPDIF Front' 100%
  mixer 0 'SPDIF Rear' 100%
  mixer 0 'SPDIF Center/LFE' 100%
  mixer 0 'Master Digital' 100%

  mixer 0 'Analog Front' 100%
  mixer 0 'Analog Rear' 100%
  mixer 0 'Analog Center/LFE' 100%

# ASRock ION 330 (and perhaps others) has 2 IEC958 channels
  mixer 0 IEC958,0 on
  mixer 0 IEC958,1 on

# ... or "simply" more soundchips
  mixer 1 IEC958,0 on
  mixer 1 IEC958,1 on
  mixer 1 IEC958,2 on
  mixer 1 IEC958,3 on

# ASRock ION 330 has Master Front set to 0
  mixer 0 'Master Front' 100%

# Shuttle XS35GT needs this too
  mixer 0 Master,0 100%


fi

exit 0
)&

