#!/bin/sh
#
# Start the oscam daemon
#
. /etc/profile
export LC_ALL=ru_RU.utf8
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
case "$1" in
  start)
    logger -t oscam "Starting oscam..."
    logger -t oscam "Waiting for network interface..."
    wait_for_network
    /usr/bin/oscam -b
    logger -t vdr "oscam started"
    ;;
  stop)
    killall oscam
    ;;
  *)
    echo $"Usage: $0 {start|stop}"
    exit 1
esac

exit $?
