#!/bin/sh
#
# Start the Video Disk Recorder
#
. /etc/profile
export LC_ALL=ru_RU.utf8
export VDR_CHARSET_OVERRIDE=ISO-8859-5
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
TERMOUT=/var/log/vdr.log
loglevel=3
VDRCMD="/usr/bin/vdr -l $loglevel.6 -P sc -P xvdr --no-kbd -d"
NoloadHTPC()
{
  grep -qse nohtpc /proc/cmdline
}
case "$1" in
  start)
    if NoloadHTPC; then
      logger -t vdr "Requested to not load VDR in command line"
      /usr/bin/chvt 2
      exit 0
    fi
    logger -t vdr "Starting Video Disk Recorder..."
    logger -t vdr "Waiting for network interface..."
    wait_for_network
    touch "$TERMOUT"
    $VDRCMD > $TERMOUT 2>&1
    logger -t vdr "VDR started"
    ;;
  stop)
    kill_vdr
    ;;
  *)
    echo $"Usage: $0 {start|stop}"
    exit 1
esac

exit $?
