#!/bin/sh
#
# Start the Video Disk Recorder
#
export LC_ALL=ru_RU.utf8
export VDR_CHARSET_OVERRIDE=ISO-8859-5
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
TERMOUT=/var/log/vdr.log
loglevel=3
VDRCMD="/usr/bin/vdr -c /etc/vdr -E /export/vdr -v /export/vdr/video -l $loglevel.6 -L /usr/lib/vdr/PLUGINS -P sc -P iptv -P xvdr --localedir=/usr/share/locale --no-kbd -d"
NetworkLoaded()
{
  ifconfig eth0 | grep -qse UP
}
NoloadHTPC()
{
  grep -qse nohtpc /proc/cmdline
}
case "$1" in
  start)
    if NoloadHTPC; then
      logger -t vdr "Requested to not load VDR in command line"
      /usr/bin/chvt 2
      exit 0
    fi
    logger -t vdr "Starting Video Disk Recorder..."
    if ! NetworkLoaded; then
      logger -t vdr "Waiting for network to load..."
      cnt=0
      while [ $cnt -lt $MODWAIT ]
      do
        cnt=$(( $cnt + 1 ))
        sleep 1
      done
      if ! NetworkLoaded; then
        logger -t vdr "Network does not work. Exit."
        exit 1
      fi
    fi
    touch "$TERMOUT"
    $VDRCMD > $TERMOUT 2>&1
    echo "OK"
    ;;
  stop)
    killall vdr
    ;;
  *)
    echo $"Usage: $0 {start|stop}"
    exit 1
esac

exit $?
